Mepts revert config removed concepts
esaude/openmrs-module-eptsreports pull request #176
Opened 2019-12-24 09:38 UTC by psmatsinhe

2019-12-24 10:05 UTC, cfaife requested changes

2019-12-24 10:05 UTC, cfaife commented on omod/src/main/resources/config.xml
> +		<property>eptsreports.reasonForRequestingViralLoadConceptUuid</property>
this concept is duplicated

2019-12-24 10:11 UTC, cfaife requested changes

2019-12-24 10:11 UTC, cfaife commented on omod/src/main/resources/config.xml
> +		<property>eptsreports.routineForRequestingViralLoadConceptUuid</property>
this concept  is duplicated

2019-12-24 10:11 UTC, cfaife commented on omod/src/main/resources/config.xml
> +		<property>eptsreports.reasonForRequestingViralLoadConceptUuid</property>
this  metadata is duplicated

2019-12-24 10:11 UTC, cfaife commented on omod/src/main/resources/config.xml
> +		<property>eptsreports.completedConceptUuid</property>
this  metadata is duplicated

2019-12-24 10:11 UTC, cfaife commented on omod/src/main/resources/config.xml
> +		<property>eptsreports.quarterlyConceptUuid</property>
this  metadata is duplicated

2019-12-24 10:11 UTC, cfaife commented on omod/src/main/resources/config.xml
> +		<property>eptsreports.routineForRequestingViralLoadConceptUuid</property>
this  metadata is duplicated

2020-01-03 09:31 UTC, ningosi commented
Closing this PR because the fixes have been done in https://github.com/esaude/openmrs-module-eptsreports/pull/180

2020-01-03 09:31 UTC, closed without merging