Mepts 325 change request in monthly report resumo mensal
esaude/openmrs-module-eptsreports pull request #185
Opened 2020-01-18 10:26 UTC by ningosi

Changes requested on MEPTS-325

2020-01-24 14:01 UTC, ynurmahomed requested changes
Compositions all look to be fine. There are some issues with the queries, please have a look.

2020-01-24 14:01 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/ResumoMensalQueries.java
> +        query, mastercardEncounterType, consultationEncounterType, preArtStarConceptId);
Mappings for the last two format strings are switched, query expects a `concept_id` then an `encounter_type_id`.

2020-01-24 14:01 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/GenericCohortQueries.java
> +  public CohortDefinition getPatientsHavingEncounterWithinDateBoundaries(int encounterType) {
Why not use `EncounterCohortDefinition` instead?

2020-01-24 14:01 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/ResumoMensalCohortQueries.java
> +            hivMetadata.getMasterCardEncounterType().getEncounterTypeId(),
It should be `hivMetadata.getMasterCardDrugPickupEncounterType()` (encounter_type 52).

2020-01-24 14:01 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/ResumoMensalCohortQueries.java
> -            getNumberOfPatientsWhoAbandonedArtDuringCurrentMonthB7(),
Old B7 CohortDefinition is only used in a unit test, maybe it should be deleted.

2020-01-24 14:01 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/ResumoMensalCohortQueries.java
> +  public CohortDefinition getNumberOfPatientsWhoAbandonedArtDuringPreviousMonthForB127A() {
This query does not seem necessary. We can always use `getNumberOfPatientsWhoAbandonedArtDuringCurrentMonthForB7` changing the parameter mappings.

2020-01-24 14:01 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/ResumoMensalQueries.java
> +            + " e.encounter_datetime <=:endDate AND e.encounter_type=%d GROUP BY p.patient_id "
Spec says by reporting `startDate`.

2020-01-24 14:01 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/ResumoMensalQueries.java
> +            + "e.location_id=:location AND e.encounter_datetime<=:endDate GROUP BY p.patient_id "
Spec says by reporting `startDate`.

2020-01-24 14:01 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/ResumoMensalCohortQueries.java
> +    cd.addParameter(new Parameter("startDate", "Start Date", Date.class));
The query does not expect a `startDate` parameter.

2020-01-27 08:55 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/ResumoMensalQueries.java
> +        query, mastercardEncounterType, consultationEncounterType, preArtStarConceptId);
Thanks, this is corrected

2020-01-27 08:58 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/GenericCohortQueries.java
> +  public CohortDefinition getPatientsHavingEncounterWithinDateBoundaries(int encounterType) {
We have had discrepancies in the numbers we get by using the reporting ORM against the native queries, but I agree we can utilize what already exists other that duplication. I will change to use that inbuilt classes from reporting framework.

2020-01-27 14:08 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/ResumoMensalCohortQueries.java
> +            hivMetadata.getMasterCardEncounterType().getEncounterTypeId(),
Fixed

2020-01-29 15:39 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/ResumoMensalCohortQueries.java
> -            getNumberOfPatientsWhoAbandonedArtDuringCurrentMonthB7(),
This was removed

2020-01-29 15:41 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/ResumoMensalQueries.java
> +            + " e.encounter_datetime <=:endDate AND e.encounter_type=%d GROUP BY p.patient_id "
StartDate is applied to the overal query after adding 90 days

2020-01-29 15:42 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/ResumoMensalQueries.java
> +            + "e.location_id=:location AND e.encounter_datetime<=:endDate GROUP BY p.patient_id "
same as above

2020-01-30 12:51 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/ResumoMensalQueries.java
> +            + " e.encounter_datetime <=:endDate AND e.encounter_type=%d GROUP BY p.patient_id "
@ningosi I'm refering to where the spec says:

> 1. Select the most recent date:
>     1. Last encounter_datetime from encounter type 18 by reporting **start date**

Please have another look.

2020-01-30 15:54 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/ResumoMensalQueries.java
> +            + " e.encounter_datetime <=:endDate AND e.encounter_type=%d GROUP BY p.patient_id "
You are right. I will change this

2020-01-31 09:21 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/GenericCohortQueries.java
> +  public CohortDefinition getPatientsHavingEncounterWithinDateBoundaries(int encounterType) {
@ningosi this CohortDefinition has no usages now

2020-01-31 09:29 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/ResumoMensalCohortQueries.java
> -            getNumberOfPatientsWhoAbandonedArtDuringCurrentMonthB7(),
@ningosi the method is still present in the `ResumoMensalCohortQueries` class

2020-01-31 09:32 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/ResumoMensalQueries.java
> +            + "e.location_id=:location AND e.encounter_datetime<=:endDate GROUP BY p.patient_id "
@ningosi from the spec:

> The most recent “Data de Levantamento” (Concept Id 23866 value_datetime-not empty/null) by reporting **start date** from encounters of type 52

2020-01-31 09:33 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/GenericCohortQueries.java
> +  public CohortDefinition getPatientsHavingEncounterWithinDateBoundaries(int encounterType) {
@ningosi sql query is still present.

2020-01-31 09:39 UTC, ningosi commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/ResumoMensalCohortQueries.java
> -            getNumberOfPatientsWhoAbandonedArtDuringCurrentMonthB7(),
fixed

2020-01-31 13:28 UTC, ynurmahomed requested changes

2020-01-31 13:28 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/ResumoMensalCohortQueries.java
> +            hivMetadata.getMasterCardEncounterType().getEncounterTypeId(),
@ningosi it should be `hivMetadata.getMasterCardDrugPickupEncounterType().getEncounterTypeId()`

2020-01-31 13:32 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/ResumoMensalCohortQueries.java
> +  public CohortDefinition getNumberOfPatientsWhoAbandonedArtDuringPreviousMonthForB127A() {
@ningosi it now only needs parameters `location` and `startDate`. Maybe `startDate` name could be changed to something like `onDate` for better understanding.

2020-01-31 14:00 UTC, ynurmahomed approved these changes

2020-01-31 14:03 UTC, merged