MEPTS-336: Updating queries according to the new specifications
esaude/openmrs-module-eptsreports pull request #194
Opened 2020-02-11 20:18 UTC by rubailly

The system will select the source with the most recent registration date (between ART Pick up date, date of registration of
Tipo de Levantamento and date of registration of Modelo diferenciado (Dispensa Trimestral or Dispensa Semestral) prior to
the reporting end date. For patients who have more than one source on the same most recent ART pick up date, consult
date with tipo de Levantamento or Dispensa Trimestral/Dispensa Semestral, the system will use only FILA to determine
patients on each ARV Dispensation Interval. if the patients has tipo de Levantamento or Modelos Diferenciados (Dispensa
Trimestral/Dispensa Semestral) on the same consultation date, the sytem will use the Tipo de Levantamento to determine
the patients on each ARV dispensation Interval.
Patients will only be counted once in each disaggregation.
● For <3 months of ARVs dispense to active patient’s on ART as:
o All active patients whose next ART pick-up is scheduled for <83 days after the date of their last ART drug pick-up
(Fila) or marked as DM on Ficha Clinica Mastercard on last Tipo de Levantamento
● For 3-5 months of ARVs dispensed to patient’s on ART as:
o All active patients whose next ART pick-up is scheduled for 83-173 days after the date of their last ART drug pick-up
(FILA) or marked as DT on Last Tipo de Levantamento on Ficha Clinica Mastercard
▪
or Last “Dispensa Trimestral (DT)” as Iniciar (I) or Manter (C)
● For 6 or more months of ARVs dispensed to active patient’s on ART:
o All active patients whose next ART pick-up is scheduled for >173 days after the date of their last ART drug pick-up
(FILA) or marked as DS on Last Tipo de Levantamento or Ficha Clinica Mastercard
or Last “Dispensa Semestral (DS)” as Iniciar (I) or Manter (C)
If the patient has last ​ QUARTERLY DISPENSATION (DT) or SEMESTRAL DISPENSATION (DS) with value COMPLETED
(id=1267) it should be retired from this indicator regardless of any other indication of being active on ART

2020-02-13 09:26 UTC, ynurmahomed commented
@rubailly please format the code before submitting the PR.

`mvn com.coveo:fmt-maven-plugin:format` or build the project

2020-02-13 09:39 UTC, ynurmahomed requested changes

2020-02-13 09:39 UTC, ynurmahomed commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxCurrCohortQueries.java
> +  public SqlCohortDefinition getPatientsWithMonthlyTypeOfDispensation(List < EncounterType > encounterTypes) {
If encounter types are always going to be:
```
    Arrays.asList(
            hivMetadata.getARVPharmaciaEncounterType(),
            hivMetadata.getAdultoSeguimentoEncounterType());
```
there is no reason to use parameters and a for loop, please inline them in the query and use String.format like all the other queries in the project.

2020-02-17 10:59 UTC, psmatsinhe requested changes

2020-02-17 10:59 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxCurrCohortQueries.java
> +    for (EncounterType et : encounterTypes) {
I think we need to be consistent in our approaches, all other queries we kept the encounterIds in line not in a loop, I suggest to use the same approach here
@rubailly

2020-02-17 10:59 UTC, psmatsinhe commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TxCurrCohortQueries.java
> +            + hivMetadata.getReturnVisitDateForArvDrugConcept().getConceptId()
@rubailly Also use the % notation for variables to pass on queries

2020-02-18 07:11 UTC, psmatsinhe approved these changes

2020-02-18 07:29 UTC, merged