MEPTS-371 Changes in Tx-TB Denominator - Screened for TB
esaude/openmrs-module-eptsreports pull request #237
Opened 2020-03-05 06:54 UTC by simaomazive

2020-03-10 12:41 UTC, amosh101 commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/queries/TXTBQueries.java
> +            + "ON p.patient_id = e.patient_id"
Queries need blank space whenever breaking on new lines since + is concatenation.

2020-03-10 12:41 UTC, amosh101 requested changes
Requires small changes.

2020-03-12 09:12 UTC, amosh101 requested changes
Small changes required.

2020-03-12 09:13 UTC, amosh101 commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TXTBCohortQueries.java
> +            + "OR (tuberculosis-symptomys OR active-tuberculosis OR tb-observations OR application-for-laboratory-research OR tb-genexpert-test OR culture-test"
Please check the blank spaces after the concatenate signal + here on composition query.

2020-03-12 09:13 UTC, amosh101 commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TXTBCohortQueries.java
> +            + "OR test-tb-lam) OR result-for-basiloscopia))"
Here as well

2020-03-12 09:13 UTC, amosh101 commented on api/src/main/java/org/openmrs/module/eptsreports/reporting/library/cohorts/TXTBCohortQueries.java
>              + "NOT ((transferred-out NOT (started-tb-treatment OR in-tb-program)) OR started-tb-treatment-previous-period OR in-tb-program-previous-period)");
and here

2020-03-16 08:17 UTC, rubailly commented
TGTM

2020-03-16 08:17 UTC, merged